#!/bin/bash

abshere=$(readlink -f "$BASH_SOURCE")
absdir=$(dirname $abshere)

cd $absdir

#git pull << EOF
#yes
#yes
#EOF

uname=$(whoami)

# requires: autoconf  libtool  libreadline-dev

sudo apt-get update
sudo apt-get install -y zip make cmake g++ autoconf libtool  libreadline-dev automake curl unzip
mkdir ext
cd ext

#zookeeper
wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
tar xzf zookeeper-3.4.6.tar.gz
rm zookeeper-3.4.6.tar.gz
mv zookeeper-3.4.6/src/c zookeeper
rm -fr zookeeper-3.4.6
cd zookeeper
./configure --prefix=${absdir}/ext/zookeeper/
make -j
make install
cd ..

# protobuf
#wget https://github.com/protocolbuffers/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
wget https://github.com/protocolbuffers/protobuf/releases/download/v2.4.1/protobuf-2.4.1.tar.gz
#tar xzf protobuf-2.6.1.tar.gz
tar xzf protobuf-2.4.1.tar.gz
#mv protobuf-2.6.1 protobuf
mv protobuf-2.4.1 protobuf
cd protobuf
./autogen.sh
./configure --prefix=${absdir}/ext/protobuf/
make -j
make install
cd ..

# googletest
wget https://github.com/google/googletest/archive/release-1.6.0.zip
unzip release-1.6.0.zip
rm release-1.6.0.zip
mv googletest-release-1.6.0 googletest
cd googletest
mkdir build && cd build 
cmake ../ && make -j
cd ../../

# zeromq
wget https://archive.org/download/zeromq_2.1.11/zeromq-2.1.11.tar.gz
tar xzf zeromq-2.1.11.tar.gz
rm zeromq-2.1.11.tar.gz
mv zeromq-2.1.11 zeromq
cd zeromq
./autogen.sh
./configure --prefix=${absdir}/ext/zeromq/
make -j
# no need to install to other placd
sudo make install
cd ..


#ld_str="/users/${uname}/calvin/ext/protobuf/src/.libs:/users/${uname}/calvin/ext/zookeeper/.libs:/users/${uname}/calvin/ext/googletest/lib/.libs:/usr/local/lib:/usr/lib:/users/${uname}/calvin/ext/zeromq/lib"

ld_str="/users/${uname}/calvin/ext/protobuf/lib/:/users/${uname}/calvin/ext/zookeeper/lib/:/users/${uname}/calvin/ext/googletest/lib/.libs/:/usr/local/lib/:/usr/lib/:/users/${uname}/calvin/ext/zeromq/lib/"
echo LD_LIBRARY_PATH="\""${ld_str}"\"" | sudo tee /etc/environment

#sudo source /etc/environment
sudo bash -c "source /etc/environment"
