#!/bin/bash

# requires: autoconf  libtool  libreadline-dev

sudo apt-get update
sudo apt-get install -y zip make cmake g++ autoconf libtool  libreadline-dev automake curl unzip
mkdir ext
cd ext

#zookeeper
wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
tar xzf zookeeper-3.4.6.tar.gz
rm zookeeper-3.4.6.tar.gz
mv zookeeper-3.4.6/src/c zookeeper
rm -fr zookeeper-3.4.6
cd zookeeper
./configure --prefix=$PWD
make -j
cd ..

# googletest
wget https://src.fedoraproject.org/lookaside/pkgs/gtest/gtest-1.6.0.zip/4577b49f2973c90bf9ba69aa8166b786/gtest-1.6.0.zip
unzip gtest-1.6.0.zip
rm gtest-1.6.0.zip
mv gtest-1.6.0 googletest
cd googletest
./configure --prefix=$PWD
make -j
cd ..

# protobuf
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf
git submodule update --init --recursive
./autogen.sh
 ./configure
 make
 make check
 sudo make install
 sudo ldconfig # refresh shared library cache.
 cd ..




# zeromq
git clone https://github.com/zeromq/libzmq.git
cd libzmq
git submodule update --init --recursive
./autogen.sh
./configure
make
make check
sudo make install
cd ..



